### ISSUE TITLE
Android dependency 'androidx.exifinterface:exifinterface'

### ISSUE THREAD

**Issue by kashinathChari** [HamidrezaAmz/AndroidImageSlider#1]
Android dependency 'androidx.exifinterface:exifinterface' has different version for the compile (1.0.0-rc01) and runtime (1.1.0-alpha01) classpath. You should manually set the same version via DependencyResolution

Please help me to sortout this issue

**Comment by HamidrezaAmz** [comment]
Migrate your whole project to **AndroidX**.
