### ISSUE TITLE
Failed to resolve: com.github.HamidrezaAmz:AndroidImageSlider:v1.0.8

### ISSUE THREAD

**Issue by mohammadn0man** [HamidrezaAmz/AndroidImageSlider#2]
I got this error while adding "implementation 'com.github.HamidrezaAmz:AndroidImageSlider:v1.0.8'" dependency to my grade file.

**Comment by HamidrezaAmz** [comment]
```gradle
allprojects {
        repositories {
            maven { url 'https://jitpack.io' }
        }
    }
```

Add this into your gradle to use any library that is hosted by jitpack

**Comment by mohammadn0man** [comment]
I have already added that.
